name: Code Quality

on:
  - pull_request

jobs:
  run-quality-check:
    name: Lint, check formatting and build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Prepare Frontend
        working-directory: frontend
        run: npm ci && npx next typegen

      - name: Format Check Frontend
        working-directory: frontend
        run: npm run format:check

      - name: Format Check Common
        working-directory: common
        run: npm run format:check
      
      - name: Format Check Backend
        working-directory: backend
        run: npm ci && npm run format:check

      - name: Lint Frontend
        working-directory: frontend
        run: npm run lint
      
      - name: Lint Common
        working-directory: common
        run: npm run lint

      - name: Build frontend
        working-directory: frontend
        run: npm run build
