name: Code Quality

on:
  - pull_request

jobs:
  run-quality-check:
    name: Lint, check formatting and build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Prepare Frontend
        working-directory: frontend
        run: pnpm install --frozen-lockfile && npx next typegen

      - name: Format Check Frontend
        working-directory: frontend
        run: pnpm format:check

      - name: Format Check Common
        working-directory: common
        run: pnpm format:check
      
      - name: Format Check Backend
        working-directory: backend
        run: pnpm install --frozen-lockfile && pnpm format:check

      - name: Lint Frontend
        working-directory: frontend
        run: pnpm lint
      
      - name: Lint Common
        working-directory: common
        run: pnpm lint

      - name: Build frontend
        working-directory: frontend
        run: pnpm build
